bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '1500':'ksh2000',
  '2000':'ksh4000',
  '5000':'ksh8000',
  '9000':'10,000',
  '12000': '12+'
}

county_choices = {
        'Brn': 'Baringo',
        'Bmt': 'Bomet',
        'Bgm': 'Bungoma',
        'Bs': 'Busia',
        'Em': 'embu',
        'E-m': 'Elgeyo-Marakwet',
        'Grs': 'Garissa',
        'Hb': 'Homabay',
        'isl': 'Isiolo',
        'kjo': 'Kajiado',
        'kk': 'Kakamega',
        'krch': 'Kericho',
        'kmb': 'Kiambu',
        'klf': 'kilifi',
        'krn': 'Kirinyaga',
        'ksi': 'Kisii',
        'ktu': 'kitui',
        'ksm': 'Kisumu',
        'kwl': 'Kwale',
        'lp': 'laikipia',
        'Lm': 'lamu',
        'mks': 'machakos',
        'mkn': 'Makueni',
        'Mrs': 'marsabit',
        'Mra': 'mandera',
        'mr': 'Meru',
        'mgi': 'Migori',
        'msa': 'mombasa',
        'mua': 'Muranga',
        'Nrb': 'Nairobi',
        'Nkr': 'Nakuru',
        'Nd': 'Nandi',
        'nrk': 'Narok',
        'nyr': 'Nyamira',
        'NYa': 'Nyandarua',
        'Nri': 'Nyeri',
        'Smb': 'Samburu',
        'sy': 'siaya',
        'tt': 'taita taveta',
        'tr': 'Tana river',
        'tn': 'Tharaka Nithi',
        'Trn': 'Trans Nzoia',
        'Tra': 'Turkana',
        'usn': 'Uasin gishu',
        'Vhg': 'Vihiga',
        'wr': 'Wajir',  
        'Wp': 'West Pokot',
        
}

